#!/bin/bach

ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell
ps -aux | grep shell


